AgoratecVueloAppBundle_navigationpage:
    pattern:  /navigation
    defaults: { _controller: AgoratecVueloAppBundle:Navigation:index }

AgoratecVueloAppBundle_navigationkmlpage:
    pattern:  /navigation/kml/{lat}&{lng}
    defaults: { _controller: AgoratecVueloAppBundle:Navigation:kml }

AgoratecVueloAppBundle_adminpage:
    pattern:  /admin
    defaults: { _controller: AgoratecVueloAppBundle:Admin:index }
