AgoratecVueloAppBundle_homepage:
    pattern:  /home
    defaults: { _controller: AgoratecVueloAppBundle:Home:index }

AgoratecVueloAppBundle_navigationpage:
    pattern:  /navigation
    defaults: { _controller: AgoratecVueloAppBundle:Navigation:index }

AgoratecVueloAppBundle_navigationkmlpage:
    pattern:  /navigation/kml/{lat}&{lng}
    defaults: { _controller: AgoratecVueloAppBundle:Navigation:kml }

AgoratecVueloAppBundle_adminpage:
    pattern:  /admin
    defaults: { _controller: AgoratecVueloAppBundle:Admin:index }

usuario_login:
    pattern:  /usuario/login
    defaults: { _controller: AgoratecVueloAppBundle:Usuario:login }
    
usuario_login_check:
    pattern:  /usuario/login_check
    
usuario_logout:
    pattern:  /usuario/logout
