AgoratecVueloAppBundle_homepage:
    pattern:  /home
    defaults: { _controller: AgoratecVueloAppBundle:Home:index }

AgoratecVueloAppBundle_adminpage:
    pattern:  /admin
    defaults: { _controller: AgoratecVueloAppBundle:Admin:index }
