parameters:
#    agoratec_vuelo_app.example.class: Agoratec\VueloAppBundle\Example

services:
#    agoratec_vuelo_app.example:
#        class: %agoratec_vuelo_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
