security:
    encoders:
        Agoratec\VueloAppBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }


    providers:
        usuarios:
            entity: { class: Agoratec\VueloAppBundle\Entity\Usuario, property:login }

    firewalls:
        frontend:
            pattern: ^/
            anonymous: ~
            form_login: 
                login_path: /usuario/login
                check_path: /usuario/login_check
                default_target_path: /home
            logout:
              path: usuario_logout
              target: /home

            remember_me:
                key: cupon1234
                lifetime: 3600

            
    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }
        - { path: ^/navigation/*, roles: ROLE_USUARIO }


