security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        usuarios:
            entity: { class: Agoratec\VueloAppBundle\Entity\Usuario, property:login }

    firewalls:
        frontend:
            pattern: ^/
            anonymous: ~
            form_login: 
                login_path: /usuario/login
                check_path: /usuario/login_check
            
    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }


